# Generated by Django 3.2.8 on 2021-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productshop', '0002_auto_20211010_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=60, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=60, upload_to='products_images'),
        ),
    ]
