# Generated by Django 3.2.8 on 2021-10-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productshop', '0003_auto_20211010_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrition',
            new_name='description',
        ),
    ]
